//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDLigotea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foto
    {
        public int IdFoto { get; set; }
        public int IdUsuario { get; set; }
        public string URL { get; set; }
        public string Texto { get; set; }
        public byte Orden { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
