//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDLigotea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Fotos = new HashSet<Foto>();
            this.MensajesEnviados = new HashSet<Mensaje>();
            this.MensajesRecibidos = new HashSet<Mensaje>();
            this.Votaciones = new HashSet<Votacion>();
            this.VotacionesRecibidas = new HashSet<Votacion>();
            this.VisitasRecibidas = new HashSet<Visita>();
            this.VisitasRealizadas = new HashSet<Visita>();
        }
    
        public int IdUsuario { get; set; }
        public string Nick { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public System.DateTime Nacimiento { get; set; }
        public Nullable<int> IdRegion { get; set; }
        public Nullable<int> IdLocalidad { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public bool Genero { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> CampoNuevo { get; set; }
    
        public virtual ICollection<Foto> Fotos { get; set; }
        public virtual ICollection<Mensaje> MensajesEnviados { get; set; }
        public virtual ICollection<Mensaje> MensajesRecibidos { get; set; }
        public virtual ICollection<Votacion> Votaciones { get; set; }
        public virtual ICollection<Votacion> VotacionesRecibidas { get; set; }
        public virtual ICollection<Visita> VisitasRecibidas { get; set; }
        public virtual ICollection<Visita> VisitasRealizadas { get; set; }
    }
}
